# Generated by Django 5.1.2 on 2024-10-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0004_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='URL-фото'),
        ),
    ]
